# Generated by Django 3.2.3 on 2021-06-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mandato',
            fields=[
                ('idMandato', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Id Mandato')),
                ('montoMandato', models.CharField(max_length=50, verbose_name='Monto Mandato')),
            ],
        ),
    ]
