# Generated by Django 3.2.3 on 2021-06-30 02:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandato',
            name='codigoVerificador',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Codigo verificador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mandato',
            name='diaPago',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Dia de pago'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mandato',
            name='fechaVencimiento',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Fecha de vencimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mandato',
            name='numTarjeta',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Numero de la tarjeta'),
            preserve_default=False,
        ),
    ]
