# Generated by Django 3.2.3 on 2021-06-30 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210629_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoUsuario',
            fields=[
                ('idTipoUsuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id tipo de usuario')),
                ('tipoUsuario', models.CharField(max_length=50, verbose_name='Tipo usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=70, verbose_name='Nombre Usuario')),
                ('correoUsuario', models.CharField(max_length=50, verbose_name='Correo')),
                ('contraseñaUsuario', models.CharField(max_length=50, verbose_name='Contraseña')),
                ('tipoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipousuario')),
            ],
        ),
    ]
