# Generated by Django 3.2.3 on 2021-06-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tipousuario_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('idInsumo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Id Insumos')),
                ('nombreInsumo', models.CharField(max_length=50, verbose_name='Nombre Insumo')),
                ('claseInsumo', models.CharField(max_length=50, verbose_name='Clase Insumo')),
                ('costoInsumo', models.CharField(max_length=50, verbose_name='Costo Insumo')),
                ('fechaVencimiento', models.CharField(max_length=50, verbose_name='Fecha de vencimiento')),
            ],
        ),
    ]
